### ISSUE TITLE
Criar interface para o comprador

### ISSUE THREAD

**Issue by oEduardoAfonso** [UnBParadigmas2022-2/2022.2_G2_SMA_Barganha#5]
Atualmente só o vendedor possui uma interface, mas poderia haver também uma interface específica para os compradores, onde todos os produtos disponíveis seriam listados.

**Comment by abner423** [comment]
Essa issue foi resolvida, e algumas outras implementações podem ser encontradas e conferidas no seguinte PR:

https://github.com/UnBParadigmas2022-2/2022.2_G2_SMA_Barganha/pull/10
